//Generated by Claude 4.6 & Gemini (Refactored for Notifications & Bulletproof GPA)
const express = require('express');
const StudentVue = require('studentvue.js');

const app = express();
const port = process.env.PORT || 3000;

app.use(express.json());

function parse(data) {
  return typeof data === 'string' ? JSON.parse(data) : data;
}

function fuzzyFind(obj, keywords) {
  if (!obj) return 'N/A';
  for (const kw of keywords) {
    const foundKey = Object.keys(obj).find(k => k.toLowerCase().includes(kw.toLowerCase()));
    if (foundKey && obj[foundKey]) {
      return obj[foundKey];
    }
  }
  return 'N/A';
}

// Recursively hunts down every notification/message object hidden anywhere in the data tree
function findAllMessages(obj, results = []) {
  if (!obj || typeof obj !== 'object') return results;

  if (obj.Subject || obj.SubjectNoHTML || obj['@_Subject']) {
    results.push(obj);
    return results;
  }

  for (const key in obj) {
    if (typeof obj[key] === 'object') {
      findAllMessages(obj[key], results);
    }
  }
  return results;
}

// Hyper-aggressive recursive search that digs into objects AND arrays for any GPA values
function findGPADeep(obj) {
  if (!obj || typeof obj !== 'object') return null;

  // Handle arrays explicitly so we look through every listed item
  if (Array.isArray(obj)) {
    for (const item of obj) {
      const found = findGPADeep(item);
      if (found) return found;
    }
    return null;
  }

  for (const key in obj) {
    const val = obj[key];
    if (val === null || val === undefined) continue;

    // If the key names GPA, analyze what's inside it safely
    if (key.toLowerCase().includes('gpa')) {
      if (typeof val !== 'object') {
        return val; 
      }
      
      // Look for common primitive leaf values inside the object
      const leaf = val.Value || val['@_Value'] || val.Score || val['@_Score'] || val['#text'];
      if (leaf && typeof leaf !== 'object') return leaf;

      // Dig deeper inside this specific GPA object/array block
      const innerFound = findGPADeep(val);
      if (innerFound) return innerFound;
    }

    // Standard recursive fallback to hunt deeper layers
    if (typeof val === 'object') {
      const found = findGPADeep(val);
      if (found) return found;
    }
  }
  return null;
}

// Manually calculates an unweighted (or rough weighted) GPA from current term grades
function calculateTermGPAManually(grades) {
  if (!grades || grades.length === 0) return 'N/A';

  // Standard 4.0 scale mapping table
  const gradeScale = {
    'A': 4.0, 'B': 3.0, 'C': 2.0, 'D': 1.0, 'F': 0.0, 'E': 0.0
  };

  let totalPoints = 0;
  let gradedClassesCount = 0;

  for (const course of grades) {
    if (!course.grade) continue;

    // Grab the base letter grade (e.g., converts "A-" or "B+" to "A" or "B")
    const baseLetter = course.grade.trim().charAt(0).toUpperCase();

    if (baseLetter in gradeScale) {
      let points = gradeScale[baseLetter];

      // OPTIONAL: Check course title for an Honors/AP/IB weighted GPA bump (+1.0)
      const title = course.title.toUpperCase();
      if (title.includes('AP') || title.includes('IB') || title.includes('HONORS') || title.includes('ADVANCED')) {
        points += 1.0; 
      }

      totalPoints += points;
      gradedClassesCount++;
    }
  }

  // Return average rounded to 2 decimal places
  return gradedClassesCount > 0 ? (totalPoints / gradedClassesCount).toFixed(2) : 'N/A';
}

// 1. SERVE THE USER INTERFACE
app.get('/', (req, res) => {
  res.send(`
    <!DOCTYPE html>
    <html>
    <head>
      <title>VuePoint Portal</title>
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <style>
        body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif; max-width: 800px; margin: 40px auto; padding: 20px; background: #f4f6f9; color: #333; }
        .box { border: 1px solid #e1e4e8; padding: 25px; margin-bottom: 20px; border-radius: 12px; background: white; box-shadow: 0 4px 6px rgba(0,0,0,0.05); }
        h2, h3 { margin-top: 0; color: #1e293b; }
        label { font-weight: 600; font-size: 14px; color: #475569; display: block; margin-bottom: 5px; }
        input, select, button { padding: 10px; margin: 5px 0 15px 0; width: 100%; box-sizing: border-box; border-radius: 6px; border: 1px solid #cbd5e1; font-size: 15px; }
        input:focus, select:focus { outline: none; border-color: #3b82f6; box-shadow: 0 0 0 3px rgba(59,130,246,0.15); }
        button { background: #2563eb; color: white; border: none; cursor: pointer; font-weight: bold; transition: background 0.2s; }
        button:hover { background: #1d4ed8; }

        .student-card { display: flex; align-items: center; gap: 20px; background: linear-gradient(135deg, #1e3a8a, #3b82f6); color: white; padding: 20px; border-radius: 12px; margin-bottom: 25px; }
        .student-details h3 { margin: 0 0 5px 0; color: white; font-size: 22px; }
        .student-details p { margin: 2px 0; opacity: 0.9; font-size: 14px; }

        .table-container { width: 100%; overflow-x: auto; background: white; border-radius: 12px; border: 1px solid #e1e4e8; margin-bottom: 25px; }
        table { width: 100%; border-collapse: collapse; text-align: left; }
        th { background: #f8fafc; padding: 14px; font-weight: 600; color: #64748b; border-bottom: 1px solid #e2e8f0; font-size: 13px; text-transform: uppercase; }
        td { padding: 14px; border-bottom: 1px solid #f1f5f9; font-size: 15px; }
        tr:last-child td { border-bottom: none; }

        .period-badge { background: #f1f5f9; color: #475569; padding: 4px 8px; border-radius: 6px; font-weight: bold; font-size: 13px; }
        .grade-badge { font-weight: 700; padding: 4px 10px; border-radius: 6px; display: inline-block; }
        .grade-good    { background: #dcfce7; color: #15803d; }
        .grade-warning { background: #fef9c3; color: #a16207; }
        .grade-danger  { background: #fee2e2; color: #b91c1c; }
        .unread-dot { display: inline-block; width: 8px; height: 8px; background: #2563eb; border-radius: 50%; margin-right: 6px; }

        .loading { text-align: center; color: #64748b; font-weight: 500; padding: 40px; }
      </style>
    </head>
    <body>
      <h2>VuePoint Portal</h2>

      <div class="box" id="step1">
        <label>1. Enter Zip Code</label>
        <input type="text" id="zipInput" placeholder="e.g., 00501">
        <button onclick="searchDistricts()">Search Districts</button>
        <div id="searchStatus" style="color: #ef4444; font-size: 14px; margin-top: -5px;"></div>
      </div>

      <div class="box" id="step2" style="display: none;">
        <label>2. Select District</label>
        <select id="districtSelect"></select>

        <label>Username</label>
        <input type="text" id="usernameInput" placeholder="Enter username">

        <label>Password</label>
        <input type="password" id="passwordInput" placeholder="Enter password">

        <button onclick="login()">Log In & Fetch Data</button>
      </div>

      <div id="dashboardBox" style="display: none;">
        <div id="studentContainer"></div>

        <h3>Current Grades</h3>
        <div class="table-container">
          <table>
            <thead>
              <tr>
                <th style="width: 80px;">Period</th>
                <th>Course Title</th>
                <th style="width: 140px; text-align: right;">Grade</th>
              </tr>
            </thead>
            <tbody id="gradesTableBody"></tbody>
          </table>
        </div>

        <h3>Notifications & Alerts</h3>
        <div class="table-container">
          <table>
            <thead>
              <tr>
                <th style="width: 160px;">Source</th>
                <th>Alert Details</th>
                <th style="width: 150px;">Date Received</th>
              </tr>
            </thead>
            <tbody id="notificationTableBody"></tbody>
          </table>
        </div>
      </div>

      <script>
        async function searchDistricts() {
          const zip = document.getElementById('zipInput').value;
          const status = document.getElementById('searchStatus');
          status.innerText = 'Searching...';

          const response = await fetch('/api/search?zip=' + zip);
          const data = await response.json();

          if (data.error) {
            status.innerText = data.error;
            return;
          }

          status.innerText = '';
          const select = document.getElementById('districtSelect');
          select.innerHTML = '';

          data.districts.forEach(d => {
            const option = document.createElement('option');
            option.value = d.url;
            option.text = d.name;
            select.appendChild(option);
          });

          document.getElementById('step2').style.display = 'block';
        }

        async function login() {
          const url = document.getElementById('districtSelect').value;
          const user = document.getElementById('usernameInput').value;
          const pass = document.getElementById('passwordInput').value;

          const dashboardBox = document.getElementById('dashboardBox');
          const studentContainer = document.getElementById('studentContainer');
          const gradesTableBody = document.getElementById('gradesTableBody');
          const notificationTableBody = document.getElementById('notificationTableBody');

          dashboardBox.style.display = 'block';
          studentContainer.innerHTML = '<div class="loading">Authenticating and loading secure data...</div>';
          gradesTableBody.innerHTML = '';
          notificationTableBody.innerHTML = '';

          const response = await fetch('/api/login', {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({ url, user, pass })
          });

          const result = await response.json();

          if (!result.success) {
            studentContainer.innerHTML = '<div style="color: #ef4444; padding: 20px; font-weight: bold;">Error: ' + result.message + '</div>';
            return;
          }

          document.getElementById('step1').style.display = 'none';
          document.getElementById('step2').style.display = 'none';

          // Render Student Card
          if (result.studentInfo) {
            studentContainer.innerHTML =
              '<div class="student-card">' +
                '<div class="student-details" style="flex: 1;">' +
                  '<h3>' + result.studentInfo.name + '</h3>' +
                  '<p><b>School:</b> ' + result.studentInfo.school + '</p>' +
                  '<p><b>Grade Level:</b> ' + result.studentInfo.grade + '</p>' +
                '</div>' +
                '<div style="text-align: right; background: rgba(255,255,255,0.15); padding: 12px 18px; border-radius: 10px; backdrop-filter: blur(5px);">' +
                  '<div style="font-size: 11px; text-transform: uppercase; tracking-spacing: 1px; opacity: 0.8; font-weight: bold;">Current GPA</div>' +
                  '<div style="font-size: 28px; font-weight: 800; line-height: 1.1; margin-top: 2px;">' + (result.gpa || 'N/A') + '</div>' +
                '</div>' +
              '</div>';
          } else {
            studentContainer.innerHTML = '<p>No profile info returned.</p>';
          }

          // Render Grades
          if (result.grades && result.grades.length > 0) {
            gradesTableBody.innerHTML = result.grades.map(g => {
              const cleanGrade = g.grade ? g.grade.trim().toUpperCase() : '';
              let badgeClass = 'grade-good';
              if (cleanGrade.startsWith('F') || cleanGrade.startsWith('D') || cleanGrade === 'NP') {
                badgeClass = 'grade-danger';
              } else if (cleanGrade.startsWith('C')) {
                badgeClass = 'grade-warning';
              }
              return '<tr>' +
                '<td><span class="period-badge">P' + g.period + '</span></td>' +
                '<td><b>' + g.title + '</b></td>' +
                '<td style="text-align: right;"><span class="grade-badge ' + badgeClass + '">' + g.grade + ' (' + g.raw + '%)</span></td>' +
              '</tr>';
            }).join('');
          } else {
            gradesTableBody.innerHTML = '<tr><td colspan="3" style="text-align:center; color:#64748b;">No gradebook data found.</td></tr>';
          }

          // Render Notifications
          if (result.notifications && result.notifications.length > 0) {
            notificationTableBody.innerHTML = result.notifications.map(n => {
              const unread = n.read === 'false' || n.read === false;
              return '<tr style="' + (unread ? 'font-weight: bold;' : '') + '">' +
                '<td>' + (unread ? '<span class="unread-dot"></span>' : '') + n.from + '</td>' +
                '<td>' + n.subject + '</td>' +
                '<td style="color: #64748b; font-size: 13px;">' + n.date + '</td>' +
              '</tr>';
            }).join('');
          } else {
            notificationTableBody.innerHTML = '<tr><td colspan="3" style="text-align:center; color:#64748b;">No system alerts or notifications found.</td></tr>';
          }
        }
      </script>
    </body>
    </html>
  `);
});

// 2. API ENDPOINT: Search Districts
app.get('/api/search', async (req, res) => {
  const zip = req.query.zip;
  if (!zip) return res.status(400).json({ error: "No zip code provided" });

  try {
    const rawResults = await StudentVue.getDistrictUrls(zip.trim());
    const results = parse(rawResults);
    const districts = results?.DistrictLists?.DistrictInfos?.DistrictInfo;

    if (!districts) {
      return res.status(404).json({ error: "No districts found for that zip code." });
    }

    const districtList = Array.isArray(districts) ? districts : [districts];
    const cleanList = districtList.map(d => ({
      name: d.Name || 'Unknown',
      url: d.PvueURL || 'N/A'
    }));

    res.json({ districts: cleanList });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

// 3. API ENDPOINT: Login, Fetch Grades + Student Info + Notifications
app.post('/api/login', async (req, res) => {
  const { url, user, pass } = req.body;
  if (!url || !user || !pass) return res.status(400).json({ success: false, message: "Missing credentials." });

  try {
    const client = await StudentVue.login(url, user, pass);

    // Student Info
    const infoData = await client.getStudentInfo();
    const parsedInfo = parse(infoData);
    const info = parsedInfo?.StudentInfo;
    let studentInfo = null;
    if (info) {
      studentInfo = {
        name:   fuzzyFind(info, ['formattedname', 'displayname', 'name']),
        grade:  fuzzyFind(info, ['grade']),
        school: fuzzyFind(info, ['schoolname', 'currentschool', 'organization', 'school', 'org', 'campus'])
      };
    }

   // Grades & GPA (FIXED: Parsed objects passed correctly, handling array recursion)
    const gradeData = await client.getGradebook();
    const parsedGradebook = parse(gradeData);
    const gradebookRoot = parsedGradebook?.Gradebook;
    const courses = gradebookRoot?.Courses?.Course;
    
    // Deep scan across BOTH structures to find hidden values
    let discoveredGpa = findGPADeep(parsedGradebook) || findGPADeep(parsedInfo);
    
    // Fallback adjustment
    let finalGpa = (discoveredGpa && discoveredGpa !== 'N/A') ? String(discoveredGpa).trim() : 'N/A';

    let grades = [];
    if (courses) {
      const courseList = Array.isArray(courses) ? courses : [courses];
      grades = courseList.map(course => {
        const currentMark = course.Marks?.Mark?.[0] || course.Marks?.Mark;
        return {
          title:  course.Title  || 'Unknown',
          period: course.Period || '?',
          grade:  currentMark?.CalculatedScoreString || 'N/A',
          raw:    currentMark?.CalculatedScoreRaw    || 'N/A'
        };
      });
    }

    // NEW: If official server GPA is blocked, calculate the local Term GPA
    if (finalGpa === 'N/A' && grades.length > 0) {
      finalGpa = calculateTermGPAManually(grades) + " (Term Est.)";
    }

    // Notifications
    const mailData = await client.getMessages();
    const parsedMail = parse(mailData);
    const discoveredMessages = findAllMessages(parsedMail);
                     
    let notifications = [];
    if (discoveredMessages && discoveredMessages.length > 0) {
      notifications = discoveredMessages.map(m => ({
        from:    m.From       || m['@_From']       || m.Module  || 'System Alert',
        subject: m.Subject    || m['@_Subject']    || m.SubjectNoHTML || '(No Content)',
        date:    m.BeginDate  || m['@_BeginDate']  || '',
        read:    String(m.Read || m['@_Read'] || 'false').toLowerCase() === 'true' ? 'true' : 'false'
      }));
    }

    res.json({ success: true, studentInfo, grades, gpa: finalGpa, notifications });

  } catch (err) {
    res.status(500).json({ success: false, message: err.message });
  }
});

app.listen(port, () => {
  console.log(`Web interface running! Go to: http://localhost:${port}`);
});