//Generated by Claude 4.6 (Merged from PhotoFetchTest.js, LoginTest.js, and DistrictSearchTest.js)
const express = require('express');
const StudentVue = require('studentvue.js');

const app = express();
const port = 3000;

// Middleware to understand JSON data sent from the browser
app.use(express.json());

function parse(data) {
  return typeof data === 'string' ? JSON.parse(data) : data;
}
//Generated Using Gemini 3.1 Pro
// 1. SERVE THE USER INTERFACE
app.get('/', (req, res) => {
  res.send(`
    <!DOCTYPE html>
    <html>
    <head>
      <title>StudentVue Login</title>
      <style>
        body { font-family: sans-serif; max-width: 600px; margin: 40px auto; padding: 20px; line-height: 1.6; }
        .box { border: 1px solid #ccc; padding: 20px; margin-bottom: 20px; border-radius: 8px; background: #f9f9f9; }
        input, select, button { padding: 8px; margin: 5px 0 15px 0; width: 100%; box-sizing: border-box; }
        button { background: #007bff; color: white; border: none; cursor: pointer; font-weight: bold; }
        button:hover { background: #0056b3; }
        pre { background: #222; color: #0f0; padding: 15px; border-radius: 5px; overflow-x: auto; }
      </style>
    </head>
    <body>
      <h2>StudentVue Portal</h2>

      <div class="box" id="step1">
        <label><b>1. Enter Zip Code:</b></label>
        <input type="text" id="zipInput" placeholder="e.g., 98006">
        <button onclick="searchDistricts()">Search Districts</button>
        <div id="searchStatus" style="color: red;"></div>
      </div>

      <div class="box" id="step2" style="display: none;">
        <label><b>2. Select District:</b></label>
        <select id="districtSelect"></select>

        <label><b>Username:</b></label>
        <input type="text" id="usernameInput" placeholder="s-raja">

        <label><b>Password:</b></label>
        <input type="password" id="passwordInput" placeholder="Enter password">

        <button onclick="login()">Log In & Fetch Data</button>
      </div>

      <div id="outputBox" style="display: none;">
        <h3>Results:</h3>
        <pre id="outputText">Waiting...</pre>
      </div>

      <script>
        async function searchDistricts() {
          const zip = document.getElementById('zipInput').value;
          const status = document.getElementById('searchStatus');
          status.innerText = 'Searching...';

          const response = await fetch('/api/search?zip=' + zip);
          const data = await response.json();

          if (data.error) {
            status.innerText = data.error;
            return;
          }

          status.innerText = '';
          const select = document.getElementById('districtSelect');
          select.innerHTML = '';

          data.districts.forEach(d => {
            const option = document.createElement('option');
            option.value = d.url;
            option.text = d.name;
            select.appendChild(option);
          });

          document.getElementById('step2').style.display = 'block';
        }

        async function login() {
          const url = document.getElementById('districtSelect').value;
          const user = document.getElementById('usernameInput').value;
          const pass = document.getElementById('passwordInput').value;
          
          const outputBox = document.getElementById('outputBox');
          const outputText = document.getElementById('outputText');
          
          outputBox.style.display = 'block';
          outputText.innerText = 'Logging in... Please wait.';

          const response = await fetch('/api/login', {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({ url, user, pass })
          });

          const resultText = await response.text();
          outputText.innerText = resultText;
        }
      </script>
    </body>
    </html>
  `);
});

// 2. API ENDPOINT: Search Districts
app.get('/api/search', async (req, res) => {
  const zip = req.query.zip;
  if (!zip) return res.status(400).json({ error: "No zip code provided" });

  try {
    const rawResults = await StudentVue.getDistrictUrls(zip.trim());
    const results = parse(rawResults);
    const districts = results?.DistrictLists?.DistrictInfos?.DistrictInfo;

    if (!districts) {
      return res.status(404).json({ error: "No districts found for that zip code." });
    }

    const districtList = Array.isArray(districts) ? districts : [districts];
    
    const cleanList = districtList.map(d => ({
      name: d.Name || 'Unknown',
      url: d.PvueURL || 'N/A'
    }));

    res.json({ districts: cleanList });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

// 3. API ENDPOINT: Login and Fetch Data
app.post('/api/login', async (req, res) => {
  const { url, user, pass } = req.body;
  if (!url || !user || !pass) return res.status(400).send("Missing credentials.");

  let output = [];
  try {
    const client = await StudentVue.login(url, user, pass);
    output.push('Logged in successfully.\n');

    // Fetch Student Info
    const infoData = await client.getStudentInfo();
    const info = parse(infoData)?.StudentInfo;

    if (!info) {
      output.push('No student info found.');
    } else {
      output.push('=== Student Info ===');
      output.push(`Name:   ${info['@_FormattedName'] || info.FormattedName || 'N/A'}`);
      output.push(`Grade:  ${info['@_Grade']         || info.Grade         || 'N/A'}`);
      output.push(`School: ${info['@_SchoolName']    || info.SchoolName    || 'N/A'}`);
    }

    // Fetch Grades
    const gradeData = await client.getGradebook();
    const courses = parse(gradeData)?.Gradebook?.Courses?.Course;

    if (!courses) {
      output.push('\nNo gradebook data found.');
    } else {
      const courseList = Array.isArray(courses) ? courses : [courses];
      output.push('\n=== Grades ===');
      courseList.forEach(course => {
        const title  = course.Title  || 'Unknown';
        const period = course.Period || '?';
        const currentMark = course.Marks?.Mark?.[0] || course.Marks?.Mark;
        const grade = currentMark?.CalculatedScoreString || 'N/A';
        const raw   = currentMark?.CalculatedScoreRaw    || 'N/A';
        
        output.push(`  [P${period}] ${title}: ${grade} (${raw}%)`);
      });
    }

    res.send(output.join('\n'));
  } catch (err) {
    res.status(500).send(`Login Error: ${err.message}`);
  }
});

app.listen(port, () => {
  console.log(`Web interface running! Go to: http://localhost:${port}`);
});