//Generated by Claude 4.6
const StudentVue = require('studentvue.js');

StudentVue.getDistrictUrls('-') 
  .then(urls => console.log('District URLs:', urls))
  .catch(err => console.error('Failed:', err));
  