//Generated by Claude 4.6
const StudentVue = require('studentvue.js');
const { inspect } = require('util');

StudentVue.login('', '', '')
  .then(client => client.getStudentInfo())
  .then(data => {
  const parsed = typeof data === 'string' ? JSON.parse(data) : data;
  console.log(JSON.stringify(parsed, null, 2));
  
});
