//Generated by Claude 4.6
const StudentVue = require('studentvue.js');
const fs = require('fs');
 
const DISTRICT_URL = '';
const USERNAME = '';
const PASSWORD = '';
 
StudentVue.login(DISTRICT_URL, USERNAME, PASSWORD)
  .then(client => client.getStudentInfo())
  .then(data => {
    const parsed = typeof data === 'string' ? JSON.parse(data) : data;
    const photo = parsed?.StudentInfo?.Photo;
 
    if (!photo) {
      console.log('No photo found in response.');
      console.log('Keys available:', Object.keys(parsed?.StudentInfo || {}));
      return;
    }
 
    const buffer = Buffer.from(photo, 'base64');
    fs.writeFileSync('student-photo.png', buffer);
    console.log('Photo saved to student-photo.png');
  })
  .catch(err => console.error('Error:', err));